SELECT TPF.LIST_ID || '51' FEE_ID,
       'F302' FEE_TYPE,
       PKG_LIFE_TDP_MAIN.F_GET_PACKAGE_MAP_CODE(TPF.PRODUCT_ID) AS COVERAGEPACKAGECODE,
       PKG_LIFE_TDP_MAIN.F_GET_PRODUCT_MAP_CODE(TPF.PRODUCT_ID) AS COMCOVERAGECODE,
       TO_CHAR(TPF.INSERT_TIME, 'YYYY-MM-DD') CONFIRM_DATE,
       TPF.PRODUCT_ID
  FROM T_PRODUCT_FEE TPF, T_CLAIM_CASE TCC
 WHERE TCC.CASE_ID = ?
   AND TCC.CASE_ID = TPF.CASE_ID
   AND TPF.FEE_TYPE = 51
   AND TPF.PRODUCT_ID = ?
UNION
SELECT '-1' fee_id,
       'F107' FEE_TYPE,
       PKG_LIFE_TDP_MAIN.F_GET_PACKAGE_MAP_CODE(TPF.PRODUCT_ID) AS COVERAGEPACKAGECODE,
       PKG_LIFE_TDP_MAIN.F_GET_PRODUCT_MAP_CODE(TPF.PRODUCT_ID) AS COMCOVERAGECODE,
       TO_CHAR(TPF.INSERT_TIME, 'YYYY-MM-DD') CONFIRM_DATE,
       TPF.PRODUCT_ID
  FROM T_PRODUCT_FEE TPF, T_CLAIM_CASE TCC
 WHERE TCC.CASE_ID = ?
   AND TCC.CASE_ID = TPF.CASE_ID
   AND TPF.FEE_TYPE = 51
   AND TPF.PRODUCT_ID = ?
   AND ROWNUM = 1
UNION
SELECT TPF.LIST_ID || '51' FEE_ID,
       'F302' FEE_TYPE,
       PKG_LIFE_TDP_MAIN.F_GET_PACKAGE_MAP_CODE(TPF.PRODUCT_ID) AS COVERAGEPACKAGECODE,
       PKG_LIFE_TDP_MAIN.F_GET_PRODUCT_MAP_CODE(TPF.PRODUCT_ID) AS COMCOVERAGECODE,
       TO_CHAR(TPF.INSERT_TIME, 'YYYY-MM-DD') CONFIRM_DATE,
       TPF.PRODUCT_ID
  FROM T_PRODUCT_FEE TPF, T_CLAIM_CASE TCC
 WHERE TCC.CASE_ID = ?
   AND TCC.CASE_ID = TPF.CASE_ID
   AND TPF.FEE_TYPE = 51
   AND TPF.PRODUCT_ID <> ?
