create table T_POLICY
(
  policy_id            NUMBER(10) not null,
  policy_code          VARCHAR2(20),
  send_code            VARCHAR2(20) not null,
  branch_id            VARCHAR2(40),
  head_id              VARCHAR2(40),
  hold_date            DATE,
  holder_id            NUMBER(10),
  holder_age           NUMBER(3),
  validate_date        DATE,
  send_date            DATE,
  p_state_id           NUMBER(3),
  agent_id             NUMBER(10),
  sign_id              NUMBER(10),
  check_id             NUMBER(10),
  pay_mode             NUMBER(2) default 1,
  bank_account         VARCHAR2(40),
  insert_time          DATE default SYSDATE not null,
  recorder_id          NUMBER(10),
  user_id              NUMBER(10),
  update_time          DATE,
  updater_id           NUMBER(10),
  accept_date          DATE,
  inspect_time         DATE,
  inspector_id         NUMBER(10),
  checkout_time        DATE,
  end_time             DATE,
  high_policy          CHAR(1) default 'N' not null,
  auto_end             DATE,
  man_start            DATE,
  wait_reply           DATE,
  reply_end            DATE,
  process_end          DATE,
  checking_id          NUMBER(10),
  address_2            VARCHAR2(200),
  zip_2                VARCHAR2(10),
  tel_2                VARCHAR2(40),
  job_1                VARCHAR2(200),
  job_2                VARCHAR2(40),
  job_code             VARCHAR2(20),
  job_cate_id          NUMBER(10),
  job_class_1          NUMBER(2),
  group_single         CHAR(1) default '2',
  pay_next             NUMBER(2),
  deliver_type         CHAR(1),
  policy_type          CHAR(1) default '1' not null,
  organ_id             VARCHAR2(40),
  period_prem          NUMBER(12,2) default 0 not null,
  normal_prem          NUMBER(12,2) default 0 not null,
  weak_prem            NUMBER(12,2) default 0 not null,
  job_prem             NUMBER(12,2) default 0 not null,
  disable_prem         NUMBER(12,2) default 0 not null,
  relation_id          NUMBER(2),
  first_notion         VARCHAR2(1000),
  group_policy_id      NUMBER(10),
  inspect_prompt       VARCHAR2(1000),
  balance_prem         NUMBER(12,2) default 0 not null,
  over_manage          CHAR(1) default '2' not null,
  recorder_prompt      VARCHAR2(1000),
  level_id             NUMBER(2) default 1 not null,
  em_life              NUMBER(4) default 0 not null,
  em_ill               NUMBER(4) default 0 not null,
  receipt_code         VARCHAR2(200),
  overdue_manage       CHAR(1),
  first_id             NUMBER(10),
  pay_way              VARCHAR2(2),
  policy_year          NUMBER(2) default 1 not null,
  policy_period        NUMBER(4) default 1 not null,
  assumpsit            VARCHAR2(4000),
  check_note           VARCHAR2(1000),
  next_time            DATE,
  service_type         CHAR(1) default '3',
  pause_time           DATE,
  company_prem         NUMBER(12,2) default 0,
  empployee_prem       NUMBER(12,2) default 0,
  insurant_num         NUMBER(10),
  sys_lock_time        DATE,
  sys_locker_id        NUMBER(10),
  sys_lock_status      CHAR(1) default '0' not null,
  discount_prem        NUMBER(12,2) default 0 not null,
  dept_id              VARCHAR2(20),
  money_id             NUMBER(6) default 1 not null,
  transfer_data        CHAR(1) default 'N' not null,
  record_end           DATE,
  normal_stand         NUMBER(12,2) default 0 not null,
  weak_stand           NUMBER(12,2) default 0 not null,
  job_stand            NUMBER(12,2) default 0 not null,
  disable_stand        NUMBER(12,2) default 0 not null,
  bank_code            VARCHAR2(20),
  agency_code          VARCHAR2(20),
  agency_hand          NUMBER(10),
  branch_bank          VARCHAR2(20),
  nb_agency_code       VARCHAR2(20),
  appro_emp_id         NUMBER(10),
  policy_print         NUMBER(2) default 0 not null,
  receipt_print        NUMBER(2) default 0 not null,
  print_time           DATE,
  sell_way             VARCHAR2(2) default '0',
  tax_prem             NUMBER(12,2) default 0 not null,
  answer_type          VARCHAR2(1) default '0' not null,
  is_answered          VARCHAR2(1) default 'N' not null,
  auto_decision        NUMBER(2) default 0 not null,
  policy_prem          NUMBER(12,2) default 0 not null,
  policy_stand         NUMBER(12,2) default 0 not null,
  address_2_2          VARCHAR2(100),
  address_2_3          VARCHAR2(100),
  address_2_4          VARCHAR2(100),
  tax_prem_stand       NUMBER(12,2) default 0 not null,
  matu_pay_mode        NUMBER(2),
  matu_process         VARCHAR2(1),
  insurant_id          NUMBER(10),
  benefit_level        VARCHAR2(4),
  cpf_account          VARCHAR2(40),
  campaign_code        VARCHAR2(10),
  policy_ref           VARCHAR2(20),
  master_num           NUMBER(10),
  relation_m           NUMBER(2),
  derivation           CHAR(1) default '1' not null,
  former_id            NUMBER(10),
  full_declare         CHAR(1) default 0 not null,
  return_time          DATE,
  return_id            NUMBER(10),
  discount_tax         NUMBER(12,2) default 0 not null,
  pending_cause        VARCHAR2(2),
  first_end            DATE,
  commission_rate      NUMBER(4,3) default 0 not null,
  answer_assumpsit     VARCHAR2(1000),
  emp_no               VARCHAR2(40),
  scan_time            DATE default sysdate,
  issue_way            NUMBER(10) default 1,
  uw_notes             VARCHAR2(4000),
  first_user_id        NUMBER(10),
  answer_tel           VARCHAR2(40),
  company_id           NUMBER(10),
  dou_emp_insured_indi CHAR(1),
  hi_plan_id           NUMBER(10),
  p_source_type        CHAR(1),
  init_prem            NUMBER(12,2),
  actual_discount_rate NUMBER(14,4),
  rate_table_prem      NUMBER(12,2),
  accept_prompt        VARCHAR2(1000),
  air_code             VARCHAR2(20),
  second_develop       CHAR(1),
  agriculture_net      CHAR(1),
  policy_input_source  VARCHAR2(5) default 0,
  is_relocate          CHAR(1),
  is_upload            CHAR(1),
  notes                VARCHAR2(2000),
  is_switch_policy     CHAR(1),
  unite_system_check   CHAR(1),
  is_relation_business CHAR(1),
  is_optimal_policy    VARCHAR2(1),
  nb_agency_sales_id   NUMBER(10),
  is_endowment         VARCHAR2(1)
)